#default params
trigger_num: 1
status_num: 1
status_th_num: 4

status_th0: 400
status_th1: 450
status_th2: 500
status_th3: 550
status_th4: 600

output_normally_on: false
input_normally_on: false

#pump specific params
suction_pump1:

  trigger_gpio0: "O_1"
  status_aio0: "InputValue_1"


suction_pump2:

  trigger_gpio0: "O_2"
  status_aio0: "InputValue_2"

suction_pump3:

  trigger_gpio0: "O_3"
  status_aio0: "InputValue_3"

suction_pump4:

  trigger_gpio0: "O_4"
  status_aio0: "InputValue_4"